export interface CLNState {
  id: number,
  pH: string,
  bod: string,
  cod: string,
  toc: string,
  tss: string,
  do: string,
  tongPhosphor: string,
  tongNito: string,
  chiorophylla: string,
  tongColiform: string,
  coliformChiuNhiet: string,
  mucPLCLNuoc: string,
}
